# Generated by Django 3.1.14 on 2022-08-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя на русском')),
                ('title_en', models.CharField(max_length=200, verbose_name='Имя на английском')),
                ('title_jp', models.CharField(max_length=200, verbose_name='Имя на японском')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('evolve_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_pokemons', to='pokemon_entities.pokemon', verbose_name='Предыдущая эволюция')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='Появился в')),
                ('disappeared_at', models.DateTimeField(verbose_name='Исчез в')),
                ('level', models.IntegerField(blank=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, verbose_name='Сила')),
                ('defence', models.IntegerField(blank=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
